// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNkoAx5UD9uIwF1jZL3hKk0vv5XJo6oWU',
    appId: '1:529387221525:web:20ddfa9ed3c68b94e9941c',
    messagingSenderId: '529387221525',
    projectId: 'whatsapp-backend-e3386',
    authDomain: 'whatsapp-backend-e3386.firebaseapp.com',
    storageBucket: 'whatsapp-backend-e3386.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWD8iCbDj1EsZEvAcqsoIk9-Ddbkb33ZU',
    appId: '1:529387221525:android:ead3ca405ab7d1bee9941c',
    messagingSenderId: '529387221525',
    projectId: 'whatsapp-backend-e3386',
    storageBucket: 'whatsapp-backend-e3386.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwyFzu7k9FnedZW_2kIfbzWuEPF15ebhQ',
    appId: '1:529387221525:ios:a43ad5234ba045f8e9941c',
    messagingSenderId: '529387221525',
    projectId: 'whatsapp-backend-e3386',
    storageBucket: 'whatsapp-backend-e3386.appspot.com',
    iosClientId:
        '529387221525-7u17kpfu8rv02r0b7hqk4d134feh7nl4.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsappClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwyFzu7k9FnedZW_2kIfbzWuEPF15ebhQ',
    appId: '1:529387221525:ios:a43ad5234ba045f8e9941c',
    messagingSenderId: '529387221525',
    projectId: 'whatsapp-backend-e3386',
    storageBucket: 'whatsapp-backend-e3386.appspot.com',
    iosClientId:
        '529387221525-7u17kpfu8rv02r0b7hqk4d134feh7nl4.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsappClone',
  );
}
